
// Creation de mes méta donnée 
// export const metadata = {
//   title:"Create Next App wit Me",
//   descripttion:'Generated by create next app'
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

